version: 2
jobs:
  build:
    working_directory: ~/elixir-starter-kit
    docker:
      - image: circleci/elixir:1.6
        environment:
          - MIX_ENV=test
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - restore_cache:
          keys:
            - v1-build-{{ .Branch }}
            - v1-build
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix compile
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: "deps"
      - save_cache:
          key: v1-deps-{{ .Branch }}
          paths: "deps"
      - save_cache:
          key: v1-deps
          paths: "deps"
      - save_cache:
          key: v1-build-{{ .Branch }}
          paths: "_build"
      - save_cache:
          key: v1-build
          paths: "_build"
      - run: mix test
      - run: mix credo
